apiVersion: v1
kind: Pod
metadata:
  name: controller
  labels:
    app: ilm-shipyard
spec:
  restartPolicy: Never
  containers:
  -
    name: proxy
    image: ehazlett/docker-proxy:latest
    ports:
      - containerPort: 2375
        hostPort: 2376
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: proxy-storage
    args: ["-D"]

  -
    name: controller
    image: ilmhpe/ilm:dev
    ports:
      - containerPort: 8080
        hostPort: 8082
      - containerPort: 9279
        hostPort: 9279
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: proxy-storage
    command: ["/bin/bash"]
    args: ["-c", "sleep 30 && ./shipyard -D server --rethinkdb-addr $ILM_BACKEND_SERVICE_HOST:8084 -d tcp://localhost:2375"]
    env:
      - name: CLAIR_ENDPOINT
        value: http://10.0.237.25:6060
      - name: http_proxy
        value: http://web-proxy.bbn.hpecorp.net:8080
      - name: https_proxy
        value: http://web-proxy.bbn.hpecorp.net:8080
  volumes:
    -
      name: proxy-storage
      hostPath:
        path: /var/run/docker.sock

