apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: clair-postgres
spec:
  restartPolicy: Never
  containers:
    -
      name: postgres
      image: postgres:9.4.5
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: postgres-storage
      env:
        - name: "PGDATA"
          value: "/var/lib/postgresql/data/pgdata"
        - name: "POSTGRES_PASSWORD"
          value: "postgres"
  volumes:
    -
      name: postgres-storage
      hostPath:
        path: /tmp/postgres
